apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: smart-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: smart-inventory-backend:latest
          imagePullPolicy: Never
          command: ["celery", "-A", "app.workers.tasks", "worker", "--loglevel=info", "--concurrency=2"]
          envFrom:
            - configMapRef:
                name: smart-inventory-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: smart-inventory-secrets
                  key: SECRET_KEY