apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: smart-inventory
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: smart-inventory-backend:latest
          imagePullPolicy: Never
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: smart-inventory-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: smart-inventory-secrets
                  key: SECRET_KEY
  backoffLimit: 3