apiVersion: v1
kind: Secret
metadata:
  name: smart-inventory-secrets
  namespace: smart-inventory
type: Opaque
stringData:
  SECRET_KEY: your_secret_key_here
  POSTGRES_PASSWORD: your_postgres_password_here